### ISSUE TITLE
Document our AWS account setup properly

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/aws-account-infrastructure#1]
The way we manage our AWS estate is somewhat idiosyncratic and non-obvious to anyone who isn't us (and as new people join, increasingly not us).

This ticket covers pulling out our AWS account infrastructure into a common repo, and making it easy to understand how it works.

**Comment by alexwlchan** [comment]
Okay, I think I've done as much as I think is sensible.

I'm going to pass this to the other devs now: if you start from the [README of this repo](https://github.com/wellcomecollection/aws-account-infrastructure):

* Do you understand what's here?
* Do you understand how it works?
* Does the documentation make sense?
* Would you feel confident making changes to this repo if I wasn't here?

Leave any feedback as comments on this ticket, and I'll make any changes suggested.

**Comment by agnesgaroux** [comment]
I think I'm good with points 1, 2 and 3
I was wondering what kind of changes are most routinely made to this repo. If I understand 1/2/3 correctly this handles shared IAC (ie. same set up across all accounts) that defines roles and VPCs, which should be pretty stable. So it is mostly upgrades, and the (once in a blue moon?) case of setting up a new AWS account?

**Comment by alexwlchan** [comment]
> So it is mostly upgrades, and the (once in a blue moon?) case of setting up a new AWS account?

Yeah, pretty much.
